"""Static Yahoo screener field metadata for the ``index`` and ``future`` quote types.

Captured from the Yahoo screener fields endpoint
(``/v1/finance/screener/instrument/{index,future}/fields``); the locale-specific
``ranking`` fields are omitted. yfinance ships no query class or field map for these
quote types, so the builder relies on this catalog together with a direct screener
POST (see :func:`openbb_yfinance.utils.helpers.get_custom_screener`). Enum value
options are reused from the yfinance ``*_SCREENER_EQ_MAP`` tables, which share these
field identifiers (region, sector, industry, exchange).
"""

EXTRA_SCREENER_FIELDS = {
    "future": {
        "fundamentals": ["ticker"],
        "keystats": [
            "avgdailyvol3m",
            "dayvolume",
            "eodprice",
            "fiftytwowkpercentchange",
            "intradayprice",
            "intradaypricechange",
            "open_interest",
            "percentchange",
            "region",
        ],
        "morningstar_rating": [
            "morningstar_economic_moat",
            "morningstar_last_close_price_to_fair_value",
            "morningstar_moat_trend",
            "morningstar_rating",
            "morningstar_rating_change",
            "morningstar_rating_updated_time",
            "morningstar_stewardship",
            "morningstar_uncertainty",
        ],
        "profile": ["exchange"],
        "userInsights": [
            "bearish_confidence_lower_bound",
            "bearish_count",
            "bearish_proportion",
            "bought_confidence_lower_bound",
            "bought_count",
            "bought_proportion",
            "bullish_confidence_lower_bound",
            "bullish_count",
            "bullish_proportion",
            "community_sentiment_date",
            "neutral_count",
            "neutral_proportion",
            "page_view_growth_weekly",
            "portfolio_sentiment_date",
            "sold_confidence_lower_bound",
            "sold_count",
            "sold_proportion",
            "total_commenter_count",
            "total_portfolio_active_users",
        ],
    },
    "index": {
        "fundamentals": ["ticker"],
        "keystats": [
            "avgdailyvol3m",
            "dayvolume",
            "eodprice",
            "fiftytwowkpercentchange",
            "intradayprice",
            "intradaypricechange",
            "percentchange",
            "region",
        ],
        "morningstar_rating": [
            "morningstar_economic_moat",
            "morningstar_last_close_price_to_fair_value",
            "morningstar_moat_trend",
            "morningstar_rating",
            "morningstar_rating_change",
            "morningstar_rating_updated_time",
            "morningstar_stewardship",
            "morningstar_uncertainty",
        ],
        "profile": ["exchange"],
        "sector_industry": ["industry", "sector"],
        "userInsights": [
            "bearish_confidence_lower_bound",
            "bearish_count",
            "bearish_proportion",
            "bought_confidence_lower_bound",
            "bought_count",
            "bought_proportion",
            "bullish_confidence_lower_bound",
            "bullish_count",
            "bullish_proportion",
            "community_sentiment_date",
            "neutral_count",
            "neutral_proportion",
            "page_view_growth_weekly",
            "portfolio_sentiment_date",
            "sold_confidence_lower_bound",
            "sold_count",
            "sold_proportion",
            "total_commenter_count",
            "total_portfolio_active_users",
        ],
    },
}

EXTRA_ENUM_FIELDS = {
    "future": ["exchange", "region"],
    "index": ["exchange", "industry", "region", "sector"],
}

EXTRA_CATEGORY_LABELS = {
    "fundamentals": "Fundamentals",
    "keystats": "Share Statistics",
    "morningstar_rating": "Morningstar Rating",
    "profile": "Profile",
    "sector_industry": "Sector & Industry",
    "userInsights": "User Insights",
}

EXTRA_FIELD_LABELS = {
    "avgdailyvol3m": "Average Daily 3m Volume",
    "bearish_confidence_lower_bound": "Bearish Confidence Lower Bound",
    "bearish_count": "Bearish Count",
    "bearish_proportion": "Bearish Proportion",
    "bought_confidence_lower_bound": "Bought Confidence Lower Bound",
    "bought_count": "Bought Count",
    "bought_proportion": "Bought Proportion",
    "bullish_confidence_lower_bound": "Bullish Confidence Lower Bound",
    "bullish_count": "Bullish Count",
    "bullish_proportion": "Bullish Proportion",
    "community_sentiment_date": "Community Sentiment Date",
    "dayvolume": "Day Volume",
    "eodprice": "EOD Price",
    "exchange": "Exchange",
    "fiftytwowkpercentchange": "52 Week Percent Change",
    "industry": "Industry",
    "intradayprice": "Intraday Price",
    "intradaypricechange": "Change",
    "morningstar_economic_moat": "Economic Moat",
    "morningstar_last_close_price_to_fair_value": "Last Close Price To Morningstar Fair Value Ratio",
    "morningstar_moat_trend": "Moat Trend",
    "morningstar_rating": "Morningstar Rating",
    "morningstar_rating_change": "Morningstar Rating Change",
    "morningstar_rating_updated_time": "Morningstar Ratings Updated Time",
    "morningstar_stewardship": "Stewardship",
    "morningstar_uncertainty": "Uncertainty Rating",
    "neutral_count": "Neutral Count",
    "neutral_proportion": "Neutral Proportion",
    "open_interest": "Open Interest",
    "page_view_growth_weekly": "Page Views Weekly Growth",
    "percentchange": "Percent Change",
    "portfolio_sentiment_date": "Portfolio Sentiment Date",
    "region": "Region",
    "sector": "Sector",
    "sold_confidence_lower_bound": "Sold Confidence Lower Bound",
    "sold_count": "Sold Count",
    "sold_proportion": "Sold Proportion",
    "ticker": "Symbol",
    "total_commenter_count": "Total Commenter Count",
    "total_portfolio_active_users": "Total Portfolio Active Users",
}

EXTRA_NUMBER_FIELDS = frozenset(
    [
        "avgdailyvol3m",
        "bearish_confidence_lower_bound",
        "bearish_count",
        "bearish_proportion",
        "bought_confidence_lower_bound",
        "bought_count",
        "bought_proportion",
        "bullish_confidence_lower_bound",
        "bullish_count",
        "bullish_proportion",
        "dayvolume",
        "eodprice",
        "fiftytwowkpercentchange",
        "intradayprice",
        "intradaypricechange",
        "morningstar_last_close_price_to_fair_value",
        "morningstar_rating",
        "neutral_count",
        "neutral_proportion",
        "open_interest",
        "page_view_growth_weekly",
        "percentchange",
        "sold_confidence_lower_bound",
        "sold_count",
        "sold_proportion",
        "total_commenter_count",
        "total_portfolio_active_users",
    ]
)
